### ISSUE TITLE
Piping functions specified with :: throws error

### ISSUE THREAD

**Issue by richierocks** [smbache/magrittr#78]
To reproduce:

```{r}
data.frame(x = 1:10) %>% ncol
## [1] 1
data.frame(x = 1:10) %>% base::ncol
## Error in .::base : unused argument (ncol)
```

**Comment by smbache** [comment]
This has been fixed in the github version, no?

**Comment by vincentarelbundock** [comment]
I came here to file the same bug, and I can confirm that it seems fixed in the current github version. I tried the original example as well as the one that tripped me up personally:

    library(psych)
    library(magrittr)
    psych::describe(rnorm(100))
    rnorm(100) %>% psych::describe

**Comment by ctbrown** [comment]
It is unfortunate that the github and CRAN have the same version number (1.5); since they are clearly different.  To fix this issue you must install from github,:

> devtools::install_github("tidyverse/magrittr")

**Comment by LeeMendelowitz** [comment]
Thanks for the help here. Installing from GitHub resolves the issue. This is still a problem in the CRAN version of magrittr in January 2018.

**Comment by MatthieuStigler** [comment]
Seems this issue is tricking more than one person, see the issue on StackOverflow: https://stackoverflow.com/questions/54992188/r-using-pipe-and-pkgfo-leads-to-error-error-in-base-unused-argument/54992189?noredirect=1#comment96742243_54992189

**Comment by oganm** [comment]
Not sure if anyone would be peeking here after all this time but I am curious, what just happened here? For the longest time the fix was exclusive to github, it appears to have since been removed from ther etoo
